CREATE TABLE usuario (
  id SERIAL PRIMARY KEY,
  nome varchar(255) default NULL,
  email varchar(255) default NULL,
  senha varchar(255)
);

INSERT INTO usuario (nome,email,senha) VALUES ('Bethany','luctus.sit@tellusnonmagna.edu','4227'),('Brielle','ridiculus.mus@Aenean.ca','8858'),('Acton','ut.pharetra@diam.org','9470'),('Gray','ipsum@Curabitur.co.uk','8911'),('Mira','lectus.ante.dictum@Aliquameratvolutpat.ca','2770'),('Louis','dolor.sit@necleo.org','1537'),('Alexander','Nullam@non.edu','7667'),('Armand','in.tempus@eudolor.org','1923'),('Althea','Morbi.vehicula.Pellentesque@Namac.net','9313'),('Kyle','semper.auctor.Mauris@nonhendrerit.net','8416');
INSERT INTO usuario (nome,email,senha) VALUES ('Marvin','et.malesuada.fames@sodaleselit.co.uk','6209'),('Tyrone','rhoncus@lacusNullatincidunt.co.uk','9822'),('Hop','in.tempus@blandit.edu','8157'),('Amir','vitae@odioauctorvitae.ca','4870'),('Porter','est@luctusvulputate.edu','7075'),('George','eget@rhoncusNullamvelit.edu','2613'),('Fallon','Proin.dolor.Nulla@massaQuisqueporttitor.edu','2341'),('Kelly','parturient@Vivamus.edu','7596'),('Abra','fringilla.porttitor.vulputate@massaVestibulum.org','6235'),('Regan','nec@vel.com','2504');
INSERT INTO usuario (nome,email,senha) VALUES ('Oliver','montes@sagittisNullamvitae.edu','1313'),('Zeph','faucibus.orci@tinciduntcongue.co.uk','2291'),('Daryl','in.lobortis.tellus@velitduisemper.ca','4708'),('Rinah','fringilla@interdum.ca','2202'),('Bert','augue@fermentummetus.co.uk','5008'),('Jerome','aliquet@vulputaterisusa.ca','5016'),('Herrod','velit@vulputate.edu','1539'),('Hermione','eget.magna.Suspendisse@ullamcorpermagnaSed.net','8849'),('Lucian','ornare.elit@eleifendCras.com','2279'),('Duncan','purus.ac@estNunc.co.uk','5934');
INSERT INTO usuario (nome,email,senha) VALUES ('Kitra','nulla.Integer.urna@Aliquamgravidamauris.edu','9702'),('Harriet','in.faucibus.orci@dui.net','7161'),('Yael','sem.egestas.blandit@bibendum.ca','2694'),('Conan','ipsum.porta.elit@SeddictumProin.ca','1643'),('Neil','vehicula.et.rutrum@montesnascetur.edu','5237'),('Deanna','nibh.enim.gravida@rutrummagnaCras.ca','6393'),('Xander','Aenean@Maecenasliberoest.org','7498'),('Preston','Morbi.accumsan@pharetraNamac.ca','4332'),('Calvin','elit@etrutrumnon.com','8731'),('Brielle','adipiscing.enim.mi@Duis.com','6143');
INSERT INTO usuario (nome,email,senha) VALUES ('Brynne','lectus@idnunc.net','9073'),('Latifah','sit@quamCurabitur.ca','9930'),('Carolyn','lobortis@Craspellentesque.net','2352'),('Rafael','Aliquam.rutrum.lorem@felis.org','2164'),('Gabriel','leo.Morbi.neque@nuncrisus.com','3220'),('Ora','Suspendisse.commodo.tincidunt@liberoProin.org','2511'),('Knox','dictum@convallisantelectus.net','2284'),('Alan','blandit@id.com','5481'),('Veronica','adipiscing.ligula@euismod.ca','6781'),('Denise','In@faucibusorciluctus.net','5581');
INSERT INTO usuario (nome,email,senha) VALUES ('Lars','magna@Duismienim.ca','4733'),('Stewart','tellus.non.magna@aarcu.com','4925'),('Rowan','odio.a.purus@luctuset.ca','7715'),('Kelly','at.velit.Cras@Vivamussit.net','6494'),('McKenzie','Aliquam.nec.enim@enimSuspendisse.net','2118'),('Hedley','Cum@erat.co.uk','7614'),('Bianca','nec.enim@nibhlacinia.edu','4119'),('Ava','eget.ipsum@ut.ca','2012'),('Marsden','vehicula.aliquet.libero@sedturpisnec.ca','7294'),('Alexandra','a.mi.fringilla@asollicitudinorci.co.uk','6944');
INSERT INTO usuario (nome,email,senha) VALUES ('Britanney','lectus@vestibulum.org','5222'),('Freya','tortor.Nunc@posuere.co.uk','8929'),('Chadwick','ipsum.cursus@quamPellentesque.ca','9067'),('Neil','consectetuer.adipiscing@estac.com','4758'),('Desirae','mattis.semper@facilisisfacilisismagna.ca','5230'),('Cole','ac.facilisis.facilisis@eget.ca','5753'),('Althea','facilisis@sitamet.edu','5761'),('Darrel','Proin.eget@orciUtsagittis.co.uk','8991'),('MacKensie','sed@Namligula.net','1575'),('Blaine','a@massa.edu','6201');
INSERT INTO usuario (nome,email,senha) VALUES ('Kelsie','Suspendisse.tristique.neque@diamnunc.ca','9660'),('Christian','mauris@utsem.net','3875'),('Judith','quis@Quisqueac.edu','8895'),('Neve','lectus@Phasellus.ca','2807'),('Declan','tristique.senectus.et@tempus.com','6891'),('Rudyard','Cras.vehicula@tortornibh.org','3915'),('Kenyon','est.Nunc.ullamcorper@sodales.org','7884'),('Hayley','nunc.sed.libero@scelerisque.org','5192'),('Faith','nulla.ante@nisisem.co.uk','9942'),('Fredericka','ante.Maecenas@egetnisidictum.edu','5958');
INSERT INTO usuario (nome,email,senha) VALUES ('Kirk','feugiat.placerat@id.com','8481'),('Aline','ipsum.primis.in@inlobortis.edu','2427'),('Chester','libero@nibh.com','3185'),('Astra','sit.amet.nulla@ornare.ca','9685'),('Alfonso','libero@diam.ca','3291'),('Kirk','sagittis@elitNulla.com','3361'),('Rogan','Fusce.aliquam@porttitorscelerisqueneque.net','7688'),('Marny','Suspendisse.ac.metus@euismod.ca','4039'),('Aaron','mauris.Morbi@loremeumetus.com','6653'),('Callie','non@ornareIn.ca','7884');
INSERT INTO usuario (nome,email,senha) VALUES ('Zelenia','non@magna.org','8069'),('Tamekah','mi.eleifend.egestas@antebibendumullamcorper.co.uk','6149'),('Eugenia','dolor@ametlorem.com','5550'),('Joan','nulla@elementumloremut.org','6893'),('Amela','enim.Curabitur.massa@ultriciessemmagna.ca','1579'),('Cathleen','vestibulum.massa@non.co.uk','4859'),('Debra','tincidunt.congue@magnaSedeu.ca','2437'),('Christian','vel.vulputate.eu@Proinsedturpis.net','6139'),('Jakeem','diam@Duisdignissimtempor.com','7473'),('Lois','eleifend@sitametante.org','8990');
